import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List

from conv_split_exporter import export_conv_input_output_channel_splits
from package_validator import validate_package, PackageValidation
from retry_executor import execute_retry_plan, save_retry_execution
from retry_planner import plan_retries, save_retry_plan


@dataclass(frozen=True)
class BacklogExecutionItem:
    category: str
    target: str
    status: str
    output_dir: str = ""
    exported_count: int = 0
    validation_json: str = ""
    message: str = ""


@dataclass(frozen=True)
class BacklogExecution:
    backlog_json: str
    category: str
    validate: bool
    items: List[BacklogExecutionItem]


def _safe_name(name: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in name)


def _parse_conv_command_hint(hint: str) -> Dict[str, str]:
    # The backlog command hints are generated by this framework; regex parsing keeps
    # this executor independent from shell quoting.
    out: Dict[str, str] = {}
    for key in ["onnx", "node-index", "output-dir", "output-chunk-channels", "input-chunk-channels"]:
        match = re.search(rf"--{key}\s+(\S+)", hint)
        if match:
            out[key] = match.group(1)
    return out


def _parse_validate_command_hint(hint: str) -> Dict[str, str]:
    out: Dict[str, str] = {}
    for key in ["package-dir"]:
        match = re.search(rf"--{key}\s+(\S+)", hint)
        if match:
            out[key] = match.group(1)
    return out


def _region_plan_for_localization(localization_json: Path) -> Path:
    data = json.loads(localization_json.read_text(encoding="utf-8"))
    model = str(data.get("model") or "")
    if not model:
        result_path = Path(str(data.get("result_path") or ""))
        stem = result_path.stem.replace("deploy_loop_", "")
        model = stem
    report_dir = localization_json.parent
    candidate = report_dir / f"region_plan_{model}.json"
    if candidate.exists():
        return candidate
    safe = model.replace("/", ".")
    candidate = report_dir / f"region_plan_{safe}.json"
    if candidate.exists():
        return candidate
    matches = sorted(report_dir.glob(f"region_plan_*{model.split('.')[-1]}*.json"))
    if matches:
        return matches[0]
    raise FileNotFoundError(f"could not locate region plan for model '{model}' next to {localization_json}")


def execute_backlog(
    backlog_json: Path,
    category: str,
    output_root: Path,
    validate: bool = False,
    workspace: Path = Path("/root/demo"),
    work_root: str = "artifacts/rhb_auto_config_framework/work",
    run_board: bool = False,
    limit: int = 0,
) -> BacklogExecution:
    data = json.loads(backlog_json.read_text(encoding="utf-8"))
    actions = [item for item in data.get("actions", []) if item.get("category") == category]
    if limit > 0:
        actions = actions[:limit]
    items: List[BacklogExecutionItem] = []
    for action in actions:
        target = str(action.get("target") or "unknown")
        try:
            if category == "split_multi_output":
                source = Path(str(action.get("source") or ""))
                if not source.exists():
                    raise FileNotFoundError(f"missing failure localization source: {source}")
                retry_plan = plan_retries(source)
                target_safe = _safe_name(target)
                action_dir = output_root / target_safe
                action_dir.mkdir(parents=True, exist_ok=True)
                retry_plan_json = action_dir / "retry_plan.json"
                save_retry_plan(retry_plan, retry_plan_json)
                region_plan_json = _region_plan_for_localization(source)
                retry_output_dir = action_dir / "retry_exports"
                execution = execute_retry_plan(retry_plan_json, region_plan_json, retry_output_dir)
                manifest_lines = ["region_id\tonnx_path\tstatus\toutputs"]
                for exported in execution.exported_submodels:
                    outputs = ",".join(exported.output_names)
                    manifest_lines.append(f"{exported.region_id}\t{exported.onnx_path}\t{exported.status}\t{outputs}")
                manifest_path = retry_output_dir / "rhb_submodels.tsv"
                manifest_path.write_text("\n".join(manifest_lines) + "\n", encoding="utf-8")
                execution_json = action_dir / "retry_execution.json"
                save_retry_execution(execution, execution_json)
                validation_json = str(execution_json)
                if validate:
                    validation = validate_package(
                        package_dir=retry_output_dir,
                        workspace=workspace,
                        work_root=work_root,
                        run_board_flag=run_board,
                    )
                    validation_json = str(action_dir / "package_validation.json")
                    (action_dir / "package_validation.json").write_text(json.dumps(asdict(validation), indent=2), encoding="utf-8")
                items.append(
                    BacklogExecutionItem(
                        category=category,
                        target=target,
                        status="executed" if execution.executed_actions else "no_executable_action",
                        output_dir=str(retry_output_dir),
                        exported_count=len(execution.exported_submodels),
                        validation_json=validation_json,
                        message=", ".join(execution.executed_actions) or "; ".join(execution.notes),
                    )
                )
                continue
            if category == "complete_validation":
                parsed = _parse_validate_command_hint(str(action.get("command_hint") or ""))
                package_dir_text = parsed.get("package-dir", "")
                if not package_dir_text or package_dir_text == "<pkg>":
                    raise ValueError("complete_validation action does not include an executable --package-dir")
                package_dir = Path(package_dir_text)
                action_dir = output_root / _safe_name(target)
                action_dir.mkdir(parents=True, exist_ok=True)
                validation: PackageValidation = validate_package(
                    package_dir=package_dir,
                    workspace=workspace,
                    work_root=work_root,
                    run_board_flag=run_board,
                )
                validation_json = action_dir / ("package_validation_board.json" if run_board else "package_validation_local.json")
                validation_json.write_text(json.dumps(asdict(validation), indent=2), encoding="utf-8")
                items.append(
                    BacklogExecutionItem(
                        category=category,
                        target=target,
                        status="executed",
                        output_dir=str(package_dir),
                        exported_count=len(validation.items),
                        validation_json=str(validation_json),
                        message="validated with board" if run_board else "validated locally; pass --run-board for board execution",
                    )
                )
                continue
            if category != "conv_ic_oc_split":
                items.append(
                    BacklogExecutionItem(
                        category=category,
                        target=target,
                        status="skipped",
                        message=f"category {category} is not executable yet",
                    )
                )
                continue
            parsed = _parse_conv_command_hint(str(action.get("command_hint") or ""))
            source_onnx = Path(parsed["onnx"])
            node_index = int(parsed.get("node-index", "0"))
            output_dir = Path(parsed.get("output-dir") or output_root / _safe_name(target))
            output_chunk = int(parsed.get("output-chunk-channels", "32"))
            input_chunk = int(parsed.get("input-chunk-channels", "8"))
            exports = export_conv_input_output_channel_splits(
                source_onnx,
                node_index=node_index,
                output_dir=output_dir,
                output_chunk_channels=output_chunk,
                input_chunk_channels=input_chunk,
            )
            manifest_lines = ["region_id\tonnx_path\tstatus\toutputs"]
            for exported in exports:
                manifest_lines.append(f"{exported.split_id}\t{exported.onnx_path}\texported\t{exported.output_name}")
            manifest_path = output_dir / "rhb_submodels.tsv"
            manifest_path.write_text("\n".join(manifest_lines) + "\n", encoding="utf-8")
            validation_json = ""
            if validate:
                validation = validate_package(
                    package_dir=output_dir,
                    workspace=workspace,
                    work_root=work_root,
                    run_board_flag=run_board,
                )
                validation_json = str(output_dir / "package_validation.json")
                (output_dir / "package_validation.json").write_text(json.dumps(asdict(validation), indent=2), encoding="utf-8")
            items.append(
                BacklogExecutionItem(
                    category=category,
                    target=target,
                    status="executed",
                    output_dir=str(output_dir),
                    exported_count=len(exports),
                    validation_json=validation_json,
                )
            )
        except Exception as exc:
            items.append(
                BacklogExecutionItem(
                    category=category,
                    target=target,
                    status="failed",
                    message=str(exc),
                )
            )
    return BacklogExecution(
        backlog_json=str(backlog_json),
        category=category,
        validate=validate,
        items=items,
    )


def save_backlog_execution(result: BacklogExecution, path: Path) -> None:
    path.write_text(json.dumps(asdict(result), indent=2), encoding="utf-8")


def render_backlog_execution(result: BacklogExecution) -> str:
    lines = [
        "# Backlog Execution",
        "",
        f"- backlog: `{result.backlog_json}`",
        f"- category: `{result.category}`",
        f"- validate: `{result.validate}`",
        "",
        "target\tstatus\texported_count\toutput_dir\tvalidation_json\tmessage",
    ]
    for item in result.items:
        lines.append(
            f"{item.target}\t{item.status}\t{item.exported_count}\t{item.output_dir}\t{item.validation_json}\t{item.message}"
        )
    return "\n".join(lines)
