import json
import shutil
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import List

from compile_runner import CompileConfig, run_compile_cmodel
from graph_importer import import_onnx
from packer_runner import PackConfig, run_pack
from board_runner import BoardConfig, run_board


@dataclass(frozen=True)
class PackageValidationItem:
    region_id: str
    source_onnx: str
    model_name: str
    generated_module: str
    layout: str
    compile_status: str
    cmodel_status: str
    pack_returncode: int
    board_status: str
    board_all_same: str
    diagnosis: str


@dataclass(frozen=True)
class PackageValidation:
    package_dir: str
    run_board: bool
    items: List[PackageValidationItem]


def _parse_tsv(path: Path) -> List[dict]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines:
        return []
    header = lines[0].split("\t")
    rows = []
    for line in lines[1:]:
        parts = line.split("\t")
        if len(parts) < len(header):
            parts.extend([""] * (len(header) - len(parts)))
        rows.append(dict(zip(header, parts)))
    return rows


def _first_input_name_and_shape(onnx_path: Path) -> tuple:
    info = import_onnx(onnx_path)
    if not info.inputs:
        return "input0", []
    input_name = info.inputs[0]
    for node in info.nodes:
        shape = node.input_shapes.get(input_name)
        if shape:
            return input_name, [int(x) for x in shape]
    return input_name, []


def _shape_to_ifmap(shape: List[int]) -> List[int]:
    if len(shape) == 4 and shape[0] == 1:
        return shape[1:]
    if len(shape) == 3:
        return shape
    if len(shape) == 2 and shape[0] == 1:
        return [1, shape[1]]
    return shape[1:] if len(shape) > 1 else shape


def _layout_for_shape(input_name: str, shape: List[int]) -> str:
    if len(shape) == 4:
        return f"{input_name}=BCHW"
    if len(shape) == 3:
        return f"{input_name}=BWC"
    if len(shape) == 2:
        return f"{input_name}=BWC"
    return f"{input_name}=BCHW"


def _diagnose_submodel(source_onnx: Path, board_status: str, board_all_same: str) -> str:
    if board_status in {"not_run", "pass"} and board_all_same in {"", "True"}:
        return ""
    try:
        info = import_onnx(source_onnx)
    except Exception as exc:
        return f"diagnosis unavailable: {exc}"
    ops = [node.op_type for node in info.nodes]
    if ops and ops[-1] == "Resize":
        return "terminal Resize in RHB: move Resize to Host exact glue or use retrainable hardware-aligned upsample"
    risky = []
    for node in info.nodes:
        if node.op_type != "Conv":
            continue
        strides = node.attrs.get("strides")
        in_shape = next(iter(node.input_shapes.values()), []) if node.input_shapes else []
        out_shape = next(iter(node.output_shapes.values()), []) if node.output_shapes else []
        in_channels = int(in_shape[1]) if len(in_shape) >= 2 and isinstance(in_shape[1], int) else 0
        out_channels = int(out_shape[1]) if len(out_shape) >= 2 and isinstance(out_shape[1], int) else 0
        if strides in ([2, 2], [2]) and out_channels >= 32:
            risky.append(f"{node.name}: stride={strides}, out_shape={out_shape}")
        if (
            len(out_shape) == 4
            and max(in_channels, out_channels) >= 16
            and out_shape[2] <= 8
            and out_shape[3] <= 8
        ):
            risky.append(
                f"{node.name}: small_spatial_mid_high_channel, in_shape={in_shape}, out_shape={out_shape}"
            )
    if risky:
        return "high-risk Conv board pattern: " + "; ".join(risky[:3])
    if ops and ops[0] == "Relu":
        return "RHB submodel starts with Relu; keep boundary Relu on Host or start RHB region at Conv"
    if "Mul" in ops:
        return "tensor Mul/gate pattern: prefer Host gate unless board-proven"
    return "no known rule matched; run finer-grain split and update rule DB"


def _write_generated_module(module_path: Path, ifmap: List[int]) -> None:
    module_path.parent.mkdir(parents=True, exist_ok=True)
    module_path.write_text(
        "\n".join(
            [
                "# Auto-generated by rhb_auto_config package validator.",
                "import torch",
                "import torch.nn as nn",
                "",
                "input_layouts = ['CHW']",
                f"ifmap_sz = [{ifmap!r}]",
                "tensor_16 = ['.bias']",
                "op_version = 18",
                "batch_size = 1",
                "",
                "class Model(nn.Module):",
                "    def forward(self, *args):",
                "        return args[0]",
                "",
            ]
        ),
        encoding="utf-8",
    )


def validate_package(
    package_dir: Path,
    workspace: Path,
    work_root: str,
    run_board_flag: bool = False,
    board: str = "root@192.168.115.122",
    password: str = "root",
    board_work_dir: str = "/home/root/workspace/demo_vp_xj/packers/rhb_auto_probe",
) -> PackageValidation:
    rows = _parse_tsv(package_dir / "rhb_submodels.tsv")
    items: List[PackageValidationItem] = []
    generated_pkg = workspace / "models" / "generated_onnx"
    (generated_pkg / "__init__.py").parent.mkdir(parents=True, exist_ok=True)
    (generated_pkg / "__init__.py").touch()
    onnx_models_dir = workspace / "onnx_models"
    onnx_models_dir.mkdir(exist_ok=True)

    for row in rows:
        if not row.get("status", "").startswith("exported"):
            continue
        outputs_text = row.get("outputs", "")
        if "," in outputs_text:
            continue
        source_onnx = Path(row["onnx_path"])
        if not source_onnx.exists():
            continue
        input_name, shape = _first_input_name_and_shape(source_onnx)
        ifmap = _shape_to_ifmap(shape)
        safe_id = row["region_id"].replace(".", "_").replace("-", "_")
        stem = source_onnx.stem.replace(".", "_").replace("-", "_")
        module_basename = f"{stem}_{safe_id}"
        model_name = f"generated_onnx.{module_basename}"
        module_path = generated_pkg / f"{module_basename}.py"
        _write_generated_module(module_path, ifmap)
        target_onnx = onnx_models_dir / f"{model_name}.onnx"
        shutil.copy2(source_onnx, target_onnx)
        layout = _layout_for_shape(input_name, shape)
        compile_result = run_compile_cmodel(
            CompileConfig(
                model=model_name,
                workspace=str(workspace),
                output_root=f"{work_root}/compile",
                layout=layout,
                run_cv_model=False,
            )
        )
        compile_status = str(compile_result.compile.get("status", "unknown"))
        cmodel_status = str(compile_result.cmodel.get("status", "unknown"))
        pack_rc = -999
        board_status = "not_run"
        board_all_same = ""
        if compile_status == "pass" and cmodel_status in {"pass", "pass_with_warnings"}:
            compile_dir = workspace / work_root / "compile" / model_name
            packer_dir = workspace / work_root / "packer" / f"packer_{model_name}"
            pack_result = run_pack(
                PackConfig(
                    workspace=str(workspace),
                    compile_output_dir=str(compile_dir),
                    packer_output_dir=str(packer_dir),
                )
            )
            pack_rc = int(pack_result.returncode)
            if run_board_flag and pack_rc == 0:
                board_result = run_board(
                    BoardConfig(
                        packer_dir=str(packer_dir),
                        board=board,
                        password=password,
                        board_work_dir=board_work_dir,
                        log_path=str(packer_dir / "board_test.log"),
                    )
                )
                board_status = str(board_result.parsed.get("status", "unknown"))
                board_all_same = str(board_result.parsed.get("all_same", ""))
        diagnosis = _diagnose_submodel(source_onnx, board_status, board_all_same)
        items.append(
            PackageValidationItem(
                region_id=row["region_id"],
                source_onnx=str(source_onnx),
                model_name=model_name,
                generated_module=str(module_path),
                layout=layout,
                compile_status=compile_status,
                cmodel_status=cmodel_status,
                pack_returncode=pack_rc,
                board_status=board_status,
                board_all_same=board_all_same,
                diagnosis=diagnosis,
            )
        )
    return PackageValidation(package_dir=str(package_dir), run_board=run_board_flag, items=items)


def save_package_validation(result: PackageValidation, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(asdict(result), indent=2), encoding="utf-8")


def render_package_validation(result: PackageValidation) -> str:
    lines = [
        "# Package Validation",
        "",
        f"- package: `{result.package_dir}`",
        f"- run_board: {result.run_board}",
        "",
        "region\tcompile\tcmodel\tpack_rc\tboard\tall_same\tmodel\tlayout\tdiagnosis",
    ]
    for item in result.items:
        lines.append(
            f"{item.region_id}\t{item.compile_status}\t{item.cmodel_status}\t{item.pack_returncode}\t"
            f"{item.board_status}\t{item.board_all_same}\t{item.model_name}\t{item.layout}\t{item.diagnosis}"
        )
    return "\n".join(lines)
