#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-/root/demo}"
FRAMEWORK="$ROOT/artifacts/rhb_auto_config_framework"
CLI="$FRAMEWORK/rhb_auto_config/cli.py"

usage() {
    cat <<'EOF'
Usage:
  run_production_loop.sh --model NAME [--case CASE.json] [--source-root DIR] [--onnx MODEL.onnx] [--features NPZ] [--remote-profile PROFILE] [--run-board]

This is the model-family neutral AgentFlow entrypoint. It generates the
production gate plan, optional source profile, optional ONNX max-RHB search,
optional software quant diagnostics, and framework health/backlog reports.

It does not hide approximate rewrites in the runner. If a rewrite is not strict
semantic equivalence, promote it only through a compiler-aligned training graph.
EOF
}

MODEL=""
CASE=""
SOURCE_ROOT=""
ONNX=""
FEATURES=""
CHANNEL_AXIS=""
REMOTE_PROFILE=""
RUN_BOARD=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --model) MODEL="$2"; shift 2 ;;
        --case) CASE="$2"; shift 2 ;;
        --source-root) SOURCE_ROOT="$2"; shift 2 ;;
        --onnx) ONNX="$2"; shift 2 ;;
        --features) FEATURES="$2"; shift 2 ;;
        --channel-axis) CHANNEL_AXIS="$2"; shift 2 ;;
        --remote-profile) REMOTE_PROFILE="$2"; shift 2 ;;
        --run-board) RUN_BOARD=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown argument: $1" >&2; usage; exit 2 ;;
    esac
done

if [[ -z "$MODEL" ]]; then
    echo "--model is required" >&2
    usage
    exit 2
fi

echo "[1/6] production plan"
plan_args=(python "$CLI" production-plan --model "$MODEL")
if [[ -n "$CASE" ]]; then
    plan_args+=(--case "$CASE")
fi
"${plan_args[@]}"

if [[ -n "$REMOTE_PROFILE" ]]; then
    echo "[1b/6] remote training plan"
    python "$CLI" remote-train --profile "$REMOTE_PROFILE" --action plan
fi

if [[ -n "$SOURCE_ROOT" ]]; then
    echo "[2/6] source profile"
    python "$CLI" profile-source --source-root "$SOURCE_ROOT"
else
    echo "[2/6] source profile skipped"
fi

if [[ -n "$ONNX" ]]; then
    echo "[3/6] ONNX import, layout analysis, deep search"
    python "$CLI" import-onnx --onnx "$ONNX"
    python "$CLI" analyze-layout --onnx "$ONNX"
    python "$CLI" deep-search --onnx "$ONNX"
else
    echo "[3/6] ONNX search skipped"
fi

if [[ -n "$FEATURES" ]]; then
    echo "[4/6] software quant diagnostics"
    qargs=(python "$CLI" quant-diagnostics --npz "$FEATURES")
    if [[ -n "$CHANNEL_AXIS" ]]; then
        qargs+=(--channel-axis "$CHANNEL_AXIS")
    fi
    "${qargs[@]}"
else
    echo "[4/6] quant diagnostics skipped"
fi

echo "[5/6] health and rewrite backlog"
python "$CLI" health-report
python "$CLI" rewrite-backlog

echo "[6/6] board gate reminder"
if [[ "$RUN_BOARD" -eq 1 ]]; then
    echo "Run package-specific deploy-loop/validate-package commands generated by deep-search/package steps."
else
    echo "Board execution is package-specific. Use deploy-loop, validate-package, or the accepted model runner after exact/approx gate decisions are recorded."
fi
